name: sonification
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - blas=2.120
  - blas-devel=3.9.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cairo=1.16.0
  - comm=0.1.4
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=4.2.2
  - fontconfig=2.14.1
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=68.1
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - lame=3.100
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.5.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.25
  - libopus=1.3
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - numexpr=2.8.7
  - openblas=0.3.25
  - opencv=4.6.0
  - openh264=1.8.0
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.4
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.4
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.14.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - wcwidth=0.2.12
  - wheel=0.38.4
  - x264=1!152.20180806
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - contourpy==1.1.1
      - cycler==0.11.0
      - einops==0.7.0
      - filelock==3.12.4
      - fonttools==4.42.1
      - freetype-py==2.4.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gpytorch==1.11
      - h5py==3.10.0
      - hsluv==5.0.4
      - idna==3.4
      - importlib-metadata==7.0.1
      - importlib-resources==6.0.1
      - iops==0.5.1
      - jax==0.4.20
      - jax-metal==0.0.5
      - jaxlib==0.4.20
      - jaxtyping==0.2.24
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning==2.2.0.post0
      - lightning-utilities==0.10.1
      - linear-operator==0.5.2
      - llvmlite==0.42.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - memory-profiler==0.61.0
      - ml-dtypes==0.3.2
      - mouseinfo==0.1.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.1
      - numba==0.59.0
      - numpy==1.26.0
      - opt-einsum==3.3.0
      - pillow==10.0.1
      - pyautogui==0.9.54
      - pygetwindow==0.0.9
      - pyinstrument==4.6.1
      - pymsgbox==1.0.9
      - pyobjc-core==10.1
      - pyobjc-framework-cocoa==10.1
      - pyobjc-framework-quartz==10.1
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pyperclip==1.8.2
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.12
      - pyqt5-sip==12.13.0
      - pyqtgraph==0.13.3
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - python-osc==1.8.3
      - pytorch-lightning==2.2.0.post0
      - pytweening==1.0.7
      - pyyaml==6.0.1
      - quantities==0.15.0
      - requests==2.31.0
      - rubicon-objc==0.4.7
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - sympy==1.12
      - threadpoolctl==3.2.0
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchmetrics==1.3.1
      - torchvision==0.15.2
      - tqdm==4.66.2
      - typeguard==2.13.3
      - urllib3==2.0.4
      - vispy==0.14.1
      - yarl==1.9.4
      - zipp==3.17.0
